version: '3'

services:
  bot:
    build:
      context: bot
      dockerfile: Dockerfile
    env_file:
      - bot/.env
    command: "python3 inori_bot.py"
    networks:
      - frontend
    depends_on:
      - api
  api: # http://api:8001
    build:
      context: backend
      dockerfile: Dockerfile
    env_file:
      - backend/.env
    expose:
      - "8001"
    networks:
      - backend
      - frontend
    command:
      "uvicorn app:app --port 8001 --host 0.0.0.0"
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    env_file:
      - backend/.env
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "9710549312"
    ports:
      - "5433:5432"
    networks:
      - backend

networks:
  frontend:
  backend:
